### ISSUE TITLE
release to pypi?

### ISSUE THREAD

**Issue by reedstrm** [Kozea/cssselect2#2]
@SimonSapin You've created the pypi page for the project, but never pushed code there. 
Even in it's alpha state, I've found it useful in a "do large-HTML document processing under control of  (extended) CSS" project I work on. If you could push a code drop, that'd help with our automated deployment systems. Although, given https://github.com/SimonSapin/cssselect/issues/48 , I and some colleagues would be willing to take repo and pypi access and help out.

**Comment by SimonSapin** [comment]
A couple things.

* As I’ve written before I think that the approach of "translating" Selectors to XPath can not really work. See https://github.com/SimonSapin/cssselect/issues/12 for example. The code in this repo has a better approach, but there is still a big decision to make: https://github.com/SimonSapin/cssselect2/issues/1. This project has never progressed beyond its current state because I’m kinda blocked on that decision.
* I find this project interesting, but I really don’t have any time to dedicate to it at the moment. I don’t want to publish it on PyPI because that make it more like another open-source project that is expected to have users and (a) maintainer(s).

Consider this repository as being the code drop. You may use it in any way permitted by the license, including publishing it on PyPI yourself. If you do so however, please do not point to this repository as the source since I most likely won’t be able to deal with issues and PRs in a timely manner. Please make a fork and use that as the "canonical" repository instead. If you like the `cssselect2` name, I don’t mind giving it away on PyPI. (Let me know your username there.)

**Comment by reedstrm** [comment]
Thanks, that's about what expected. I agree that the xpath approach, while seductive, has both correctness and scaling issues. I was more referring to your comment about your available time, and interest in other projects. We'd be maintaining this under our project account on pypi, namely 'openstax'.

**Comment by SimonSapin** [comment]
Cool. Let me know on #1 what you end up doing regarding tree APIs :)

**Comment by liZe** [comment]
I've released version 0.1, see #5 for more information.
